sudo: false

addons:
  sauce_connect: true

language: php

php:
  - 5.5
  - 5.6
  - hhvm

env:
  global:
    - secure: LKZyCesV6xIIhlUvBGu4ZvZ8Iqy8t+TsKuu2LOS3FBoieKb3kt9/q1q/jCFjw9bMsWS01C4A5IgsceFO5+eHARUIE7gHdxbz6JJPQE5DiM/832mAWmLyBC6W1o9/S4zmkA1pWT6usvrWC5fH303ZE2bjw/f5agJBQq9ontYHbEc=
    - secure: SI082ZTIAS3Ykie6+WA1ZxOnMfgFvB5vwlh1Eld9yS7w8syoA6xK/+NvHLxTcIRlw4gExtBZ3WMvDsaXubvC+d2Rdyb4eEr7o63BsM1eQXr4nuL8v62YnLxGdjWGCyiSg2rYeFsXFEk5FFj8STJozGQwMx1f635VotZ93JuvoTY=
    - DB=mysql

before_script:
  - if [[ "$DB" == "mysql" ]]; then mysql -e "CREATE DATABASE sulu;"; fi
  - if [[ "$DB" == "pgsql" ]]; then psql -c "CREATE DATABASE sulu;" -U postgres; fi
  - cp app/Resources/pages/default.xml.dist app/Resources/pages/default.xml
  - cp app/Resources/pages/overview.xml.dist app/Resources/pages/overview.xml
  - cp app/Resources/snippets/default.xml.dist app/Resources/snippets/default.xml
  - cp app/Resources/webspaces/sulu.io.xml.dist app/Resources/webspaces/sulu.io.xml
  - composer self-update
  - composer update --prefer-dist --no-interaction
  - php app/console sulu:build dev --no-interaction
  - php app/console server:run 0.0.0.0:8000 --router=app/config/router_admin.php --env prod > /dev/null 2>&1 &

script: bin/paratest -p 2 -f

matrix:
  allow_failures:
    - php: hhvm
